version: '3.8'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=my_planner_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myplanner_secret_2024
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        while ! nc -z db 5432; do sleep 1; done &&
        echo 'Database is ready!' &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=my_planner_db
      - DB_USER=postgres
      - DB_PASSWORD=myplanner_secret_2024
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOSTS=*
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  postgres_data: