# Generated by Django 5.2.4 on 2025-08-15 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='task',
            field=models.OneToOneField(help_text='Task that this event details.', on_delete=django.db.models.deletion.CASCADE, related_name='event', to='planner.task'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='task',
            field=models.ForeignKey(help_text='Task that this reminder is for.', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='planner.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(help_text='List to which this task belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planner.typetodolist'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Primary owner of this task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Optional collaborators on this task.', related_name='collaborating_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
