# Generated by Django 5.2.5 on 2025-08-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_event_end_time_alter_event_start_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['list__name', 'title']},
        ),
    ]
