# Generated by Django 5.2.5 on 2025-08-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Priority 1'), (2, 'Priority 2'), (3, 'Priority 3'), (4, 'Priority 4')], db_index=True, default=4, help_text='1=nejvyšší, 4=nejnižší'),
        ),
    ]
