# Generated by Django 5.2.5 on 2025-09-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_remove_tag_uniq_tag_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this task.', related_name='tasks', to='planner.tag'),
        ),
    ]
